/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.todolist.guis;

import com.mycompany.todolist.dominio.AdminTareas;

/**
 *
 * @author Jose Armenta, Jose Huerta, Victor Encinas
 * Clase de frame para escribir una nueva tarea o sobreescribir una existente.
 */
public class EscribirTareaFrame extends javax.swing.JFrame {
    AdminTareas adminTareas;
    ListaTareasFrame ventanaPrincipal; 
    boolean editar;
    String descripcion, filtro;
    
    /**
     * Crea una nueva instancia de EscribirTareaFrame para agregar una nueva
     * tarea.
     *
     * @param adminTareas El administrador de tareas que gestiona las tareas.
     * @param ventanaPrincipal La ventana principal que muestra la lista de
     * tareas.
     * @param filtro El filtro actual de las tareas (pendientes y completadas).
     */
    public EscribirTareaFrame(AdminTareas adminTareas, ListaTareasFrame ventanaPrincipal, String filtro) {
        initComponents();
        this.adminTareas = adminTareas;
        this.ventanaPrincipal = ventanaPrincipal;
        this.filtro = filtro;
    }
    
    /**
     * Crea una nueva instancia de EscribirTareaFrame para editar una tarea
     * existente.
     *
     * @param adminTareas El administrador de tareas que gestiona las tareas.
     * @param ventanaPrincipal La ventana principal que muestra la lista de
     * tareas.
     * @param descripcion La descripción de la tarea que se va a editar.
     * @param filtro El filtro actual de las tareas (Pendientes, Completadas,
     * etc.).
     */
    public EscribirTareaFrame(AdminTareas adminTareas, ListaTareasFrame ventanaPrincipal, String descripcion, String filtro) {
        initComponents();
        this.descripcion = descripcion;
        this.adminTareas = adminTareas;
        this.ventanaPrincipal = ventanaPrincipal;
        this.filtro = filtro;

        txtIngresarTarea.setText(descripcion); // Mostrar la tarea a editar en el campo de texto
        editar = true;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIngresarTarea = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtIngresarTarea.setText("Ingrese la nueva tarea aquí");
        txtIngresarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngresarTareaActionPerformed(evt);
            }
        });
        txtIngresarTarea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIngresarTareaKeyPressed(evt);
            }
        });

        btnAceptar.setBackground(new java.awt.Color(0, 153, 255));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIngresarTarea, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIngresarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIngresarTareaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngresarTareaKeyPressed
        if (txtIngresarTarea.getText().equals("Ingrese la nueva tarea aquí"))
        txtIngresarTarea.setText("");
    }//GEN-LAST:event_txtIngresarTareaKeyPressed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (editar) {
            // Editar la tarea existente
            adminTareas.editarTarea(descripcion, txtIngresarTarea.getText());
           
        } else {
            // Agregar nueva tarea
            adminTareas.agregarTarea(txtIngresarTarea.getText());
        }

        ventanaPrincipal.actualizar(adminTareas);
        this.dispose();


    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * Obtener el filtro actualizado
     * @return Filtro actualizado
     */
    public String getUpdatedFilter() {
        return filtro;
    }
    
    private void txtIngresarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngresarTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngresarTareaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtIngresarTarea;
    // End of variables declaration//GEN-END:variables
}
